### ISSUE TITLE
First impression

### ISSUE THREAD

**Issue by umitkucuk** [yilmazsen/pwc-demo#2]
Above all, you should work with PRs. 🚀

1. Add `.DS_Store` file to `.gitignore` in order to ignore this file. We are doing it because we don't want to push this file to the repository.

2. You can put the `icons` folder inside of the `assets` folder. It is more clear for the file structure.

3. Check the console when you are doing something. Currently, there are some errors on the console. Check them 👍

4. Use `sass-loader` and `node-sass` as a devDependencies.
See: https://nuxtjs.org/faq/pre-processors/

5. Use `eslint` and `prettier` for clean coding.
See: https://nuxtjs.org/guide/development-tools/#eslint-and-prettier

**Comment by yilmazsen** [comment]
Above all of tasks has been done without on console error.

**Comment by yilmazsen** [comment]
Please check them
